[API-1717] Create cash machine
Thalita-ribeiro/quero-ser-clickbus pull request #1
Opened 2021-04-15 13:51 UTC by Thalita-ribeiro

# [API-1717](https://busaobr.atlassian.net/browse/API-1717) 

## Tarefa(s)
- Criar um caixa eletrônico. 

## Descrição

Nesta tarefa o usuário só vai poder tirar as notas disponíveis no meu caixa eletrônico.  

## Dependências

Não há

## Evidências
![image](https://user-images.githubusercontent.com/57602792/114879829-eb87b100-9dd7-11eb-932d-7caf4a4253af.png)

2021-04-15 14:35 UTC, MuriloMarquesSantos requested changes

2021-04-15 14:35 UTC, MuriloMarquesSantos commented on testes/cash-machine/src/Cash.java
> +
Sugestão: Poderíamos fazer testes unitários?

2021-04-16 13:09 UTC, Thalita-ribeiro commented on testes/cash-machine/src/Cash.java
> +
Fiz os testes unitários conforme sugerido.

2021-04-16 13:09 UTC, MuriloMarquesSantos approved these changes

2021-04-16 13:10 UTC, merged